### ISSUE TITLE
train_scannnet

### ISSUE THREAD

**Issue by cuge1995** [dgriffiths3/pointnet2-tensorflow2#6]
None
Epoch 1/100
Traceback (most recent call last):
  File "train_scannet.py", line 105, in <module>
    train()
  File "train_scannet.py", line 87, in train
    verbose=1
  File "/home/amax/anaconda3/envs/pointnetch/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/amax/anaconda3/envs/pointnetch/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "/home/amax/anaconda3/envs/pointnetch/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/amax/anaconda3/envs/pointnetch/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 644, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/amax/anaconda3/envs/pointnetch/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/amax/anaconda3/envs/pointnetch/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "/home/amax/anaconda3/envs/pointnetch/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/amax/anaconda3/envs/pointnetch/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 598, in call
    ctx=ctx)
  File "/home/amax/anaconda3/envs/pointnetch/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'FarthestPointSample' used by {{node pointnet_sa/FarthestPointSample}} with these attrs: [npoint=1024]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  device='GPU'

         [[pointnet_sa/FarthestPointSample]] [Op:__inference_train_function_2421]

**Comment by cuge1995** [comment]
It seems that does not work in cuda 10.2

**Comment by dgriffiths3** [comment]
I've not tried with CUDA 10.2. Do the ops compile without error? I assume you have done so already, but do you change the cuda directory in `tf_ops/compile_ops.sh` L5?

**Comment by cuge1995** [comment]
succed in cuda 10.1, thanks

**Comment by cuge1995** [comment]
the the ops compile without error, but run train.py with error

**Comment by nicolasdonati** [comment]
Hi !
I have the exact same error : tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'FarthestPointSample' used by {{node pointnet_sa/FarthestPointSample}} with these attrs: [npoint=1024]
I'm using tf 2.2, CUDA 10.1 (I tried changing it to 10.0 also). Any idea how to solve this ?

**Comment by dgriffiths3** [comment]
@nicolasdonati this is due to a compilation error from the CUDA ops. Do you get any error when compiling the ops? Also, did you make sure the path was correctly set as well? If they did you should also have `.so` files in the op folders as well.

**Comment by nicolasdonati** [comment]
I did not getting any error while compiling, in fact I could solve that sub-problem somehow I had to re-install tf gpu 2.2 with conda and not pip.

Now I'm getting another error also present in these issues : (issue #5 ) Segmentation Fault. It's not said there how to solve this I think, it is only reported where the error originates from.
I compiled with gcc 5.4 and my error reads :
Epoch 1/100
      1/Unknown - 0s 48us/step - loss: 3.0441 - sparse_categorical_accuracy: 0.1774Segmentation fault (core dumped)
also, I'm using the data you provide for scannet so if this is a problem with data type or shape, I guess it is weird because I did not change anything here.

Thank you for your quick answer !

**Comment by nicolasdonati** [comment]
I can also add that I tested both gather points and farthest point sampling and it worked fine. I really don't know where the problem is coming from ...

**Comment by dgriffiths3** [comment]
Hmm, `Segmentation Fault` usually just means the error occurred in the compiled c++/CUDA code. The code is pretty well tested, especially if you are using my data it should just run straight through. I use pip so that shouldn't be the issue either. I would guess it must be something to do with the CUDA installation / compilation. Do other tensorflow ops (i.e. conv2d) run on the gpu fine?

**Comment by nicolasdonati** [comment]
Ok for some reason now it works, I did not change anything really. It appears to sometimes fail, sometimes run for some reason. I can only guess that means sometimes it picks a shape that gives the segmentation fault. I suppose you're right, and it's some kind of version error. Anyways thank you very much for your help, and this work !
